apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      complnent: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: vinicioschiavo/multi-client
          ports:
            - containersPort: 3000
            